### PR TITLE
Fix conda env

### PR DESCRIPTION
**Pull request by jlenain**
The proposed PR, along with https://github.com/cta-observatory/ctapipe_io_nectarcam/pull/32, should address #26, and streamline the installation procedure of `nectarchain`.

### CODE REVIEW

**Comment by jlenain** [comment]
> Hi @jlenain , following the installation steps in the branch you provided for this PR, the following error occurs when trying to read a data file : `FileNotFoundError: [Errno 2] No such file or directory: /Users/fbrun/anaconda2/envs/nectarchain_pr27_env/lib/python3.8/site-packages/ctapipe_io_nectarcam/resources/NectarCam-003.camgeom.fits.gz'`
> 
> In fact, the whole "resources" folder from ctapipe_io_nectarcam is not included in the created environment. Do you know why ?

Hi @frnbrun!
Ah, good point. In order to benefit from https://github.com/cta-observatory/ctapipe_io_nectarcam/pull/32 at the same time, one should also install `ctapipe_io_nectarcam` from my branch in my fork before the PR is merged there.

One way to do it is to slightly change the installation procedure for `ctapipe_io_nectarcam` in the environment.yml file for `nectarchain` with:

```
  pip:
    - git+https://github.com/jlenain/ctapipe_io_nectarcam.git@improve-setup
```

**Comment by frnbrun** [comment]
Thanks for the feedback, @jlenain (I now get some warning about the fact that ctapipe_io_nectarcam do not have a proper version number but I guess it is normal since I took it from one of your branch)

I managed to install nectarchain following the steps from the new procedure. I then tried the notebook `notebooks/Access NectarCAM data using DIRAC API.ipynb` and it worked nicely!

I just have a few questions : 
- do we still need to have the environment-dirac.yml file ? If not, maybe the notebook I tried could be updated since it would be mentioning an outdated installation procedure ?
- the `dirac-configure` command "contain" the `dirac-proxy-init` one ? Is it possible to specify from `dirac-configure` the "nectarcam" role ?

**Comment by jlenain** [comment]
Hi @frnbrun !

>  (I now get some warning about the fact that ctapipe_io_nectarcam do not have a proper version number but I guess it is normal since I took it from one of your branch)
As long as we don't tag the `ctapipe_io_nectarcam`, this warning is normal whatever the origin.
 
> I just have a few questions :
> 
>     * do we still need to have the environment-dirac.yml file ? If not, maybe the notebook I tried could be updated since it would be mentioning an outdated installation procedure ?
You're right, we would not need the specific `environment-dirac.yml` any more. I will propose a removal of it through this PR, and update the notebook accordingly.

>     * the `dirac-configure` command "contain" the `dirac-proxy-init` one ? Is it possible to specify from `dirac-configure` the "nectarcam" role ?
The `dirac-configure` command come from DIRAC itself, and is just a one-time helper to configure a DIRAC client from a given instance (the CTA one, in our case). At this stage, there is no need to initialize a proxy with a specific role.

I hope this covers your questions.

**Review by frnbrun — APPROVED** [review]
Thanks for the modifications @jlenain

**Comment by jlenain** [comment]
Holding merge until https://github.com/cta-observatory/ctapipe_io_nectarcam/pull/32 is accepted and merged into `ctapipe_io_nectarcam`.

**Comment by jlenain** [comment]
https://github.com/cta-observatory/ctapipe_io_nectarcam/pull/32 is now merged, merging this PR as well.

**Pull request merged**
