### PR TITLE
Debugging the code after updates and adding camera monitoring module

### PR DESCRIPTION
**Pull request by hashkar**

### CODE REVIEW

**Comment by jlenain** [comment]
Hi @hashkar !
Thanks a lot, but why a new PR ? Shouldn't we follow up in https://github.com/cta-observatory/nectarchain/pull/11 ?

**Comment by hashkar** [comment]
Hi @jlenain ,
The problem is that I changed my Mac and had to download the software again. As there was lot of changes git didn't let me pull, push or merger. So I created a new git pull. This has the same changes as the last one with additional debugging.

**Comment by jlenain** [comment]
Hi @hashkar ,
OK, I understand. I am running tests right now on a couple of runs, and I think we can quickly merge this.
Thanks again!

**Comment by jlenain** [comment]
Hi @hashkar !
Many thanks again for this PR! I have run tests on a couple of runs. Everything went fine, I am merging this into `master`now.

**Pull request merged**
