### PR TITLE
Adding camera temperature monitoring to the DQM pipeline

### PR DESCRIPTION
**Pull request by hashkar**
in this pull request, the camera temperature monitoring module is added as a separate class. It find the corresponding SQL file and computes the camera's average temperature during the times of the run.

### CODE REVIEW

**Comment by hashkar** [comment]
Please hold up on this pull request for now.

**Review by jlenain — COMMENTED** [review]
Thanks a lot for these additions, @hashkar . I am testing them right now.

**Comment by jlenain** [comment]
I am getting the following error:
```
$ python start_calib.py /home/jlenain/WORK/CTA/NectarCAM/Analysis/FEBv6_tests/runs/NectarCAM.Run2784.0000.fits.fz  /home/jlenain/WORK/CTA/NectarCAM/Analysis/FEBv6_tests/runs/NectarCAM.Run2784.0001.fits.fz
['start_calib.py', '/home/jlenain/WORK/CTA/NectarCAM/Analysis/FEBv6_tests/runs/NectarCAM.Run2784.0000.fits.fz', '/home/jlenain/WORK/CTA/NectarCAM/Analysis/FEBv6_tests/runs/NectarCAM.Run2784.0001.fits.fz']
NectarCAM_Run2784
SqlFileName /home/jlenain/WORK/CTA/NectarCAM/Analysis/FEBv6_tests/runs/nectarcam_monitoring_db_2021-12-01.sqlite
/home/jlenain/local/src/python/cta-observatory/nectarchain/nectarchain/dqm/mean_waveforms.py:57: RuntimeWarning: invalid value encountered in true_divide
  self.Mwf_average = self.Mwf/self.counter_evt #get average
/home/jlenain/local/src/python/cta-observatory/nectarchain/nectarchain/dqm/mean_camera_display.py:44: RuntimeWarning: invalid value encountered in true_divide
  self.CameraAverage_overEvents = self.CameraAverage/self.counter_evt
/home/jlenain/local/src/python/anaconda/envs/nectar-dev/lib/python3.7/site-packages/numpy/core/fromnumeric.py:3420: RuntimeWarning: Mean of empty slice.
  out=out, **kwargs)
/home/jlenain/local/src/python/anaconda/envs/nectar-dev/lib/python3.7/site-packages/numpy/core/_methods.py:188: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)
/home/jlenain/local/src/python/anaconda/envs/nectar-dev/lib/python3.7/site-packages/numpy/core/_methods.py:262: RuntimeWarning: Degrees of freedom <= 0 for slice
  keepdims=keepdims, where=where)
/home/jlenain/local/src/python/anaconda/envs/nectar-dev/lib/python3.7/site-packages/numpy/core/_methods.py:222: RuntimeWarning: invalid value encountered in true_divide
  subok=False)
/home/jlenain/local/src/python/anaconda/envs/nectar-dev/lib/python3.7/site-packages/numpy/core/_methods.py:253: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)
/home/jlenain/local/src/python/anaconda/envs/nectar-dev/lib/python3.7/site-packages/numpy/core/_methods.py:190: RuntimeWarning: invalid value encountered in long_scalars
  ret = ret / rcount
Traceback (most recent call last):
  File "start_calib.py", line 165, in <module>
    processor_figure_dict, processor_figure_name_dict  = p.PlotResults(name, FigPath)
  File "/home/jlenain/local/src/python/cta-observatory/nectarchain/nectarchain/dqm/charge_integration.py", line 119, in PlotResults
    disp.image = self.image_all_average
  File "/home/jlenain/local/src/python/anaconda/envs/nectar-dev/lib/python3.7/site-packages/ctapipe/visualization/mpl_camera.py", line 317, in image
    ).format(image.shape, self.geom.pix_x.shape)
ValueError: Image has a different shape () than the given CameraGeometry (1855,)
```
on an example run (again, run number 2784). I am not sure this is related to the current PR, but does this ring a bell, @hashkar ?

**Comment by hashkar** [comment]
Hi @jlenain I can't access the folder /data/CTA/cea.fr/2021 to get this run. Do you know here I can find it so I can run some tests ?

**Comment by jlenain** [comment]
Hi @hashkar , I'll PM you on the data access.

**Comment by jlenain** [comment]
Hi @hashkar !

@fcangemi and I have performed some tests, and got some inconsistencies, depending on the tested runs:

- For the issue I reported earlier on run 2784, I think this might be due to the fact that only 2 modules were active during this run, hence the resulting image shape not matching the input camera geometry.
- Runs 2720, 2722, and 2850 are perfectly processed.
- Run 2856, on @fcangemi 's side, gives the following error:
```
python start_calib.py /Users/fcangemi/nectarchain/obs/NectarCAM.Run2856.0000.fits.fz /Users/fcangemi/nectarchain/obs/NectarCAM.Run2856.0001.fits.fz
[‘start_calib.py’, ‘/Users/fcangemi/nectarchain/obs/NectarCAM.Run2856.0000.fits.fz’, ‘/Users/fcangemi/nectarchain/obs/NectarCAM.Run2856.0001.fits.fz’]
Traceback (most recent call last):
 File “start_calib.py”, line 53, in <module>
  reader=EventSource(input_url=path)
 File “/opt/anaconda3/envs/cta/lib/python3.7/site-packages/ctapipe/io/eventsource.py”, line 122, in __new__
  subcls = cls._find_compatible_source(input_url)
 File “/opt/anaconda3/envs/cta/lib/python3.7/site-packages/ctapipe/io/eventsource.py”, line 304, in _find_compatible_source
  “\t{}“.format(input_url, [c.__name__ for c in available_classes])
ValueError: Cannot find compatible EventSource for
	url:/Users/fcangemi/nectarchain/obs/NectarCAM.Run2856.0000.fits.fz
in available EventSources:
	[‘SimTelEventSource’, ‘DL1EventSource’, ‘NectarCAMEventSource’]
```
- On my side, run 2907 throws the following error:
```
$ python $NECTARDIR/nectarchain/dqm/start_calib.py NectarCAM.Run2907.0000.fits.fz NectarCAM.Run2907.0001.fits.fz NectarCAM.Run2907.0002.fits.fz NectarCAM.Run2907.0003.fits.fz 
['/home/jlenain/local/src/python/cta-observatory/nectarchain/nectarchain/dqm/start_calib.py', 'NectarCAM.Run2907.0000.fits.fz', 'NectarCAM.Run2907.0001.fits.fz', 'NectarCAM.Run2907.0002.fits.fz', 'NectarCAM.Run2907.0003.fits.fz']
NectarCAM_Run2907
SqlFileName nectarcam_monitoring_db_2022-01-17.sqlite
Traceback (most recent call last):
  File "/home/jlenain/local/src/python/cta-observatory/nectarchain/nectarchain/dqm/start_calib.py", line 153, in <module>
    p.FinishRun()
  File "/home/jlenain/local/src/python/cta-observatory/nectarchain/nectarchain/dqm/camera_monitoring.py", line 87, in FinishRun
    TotalDrawers = np.max(self.DrawerNum2)
  File "<__array_function__ internals>", line 6, in amax
  File "/home/jlenain/local/src/python/anaconda/envs/nectar-dev/lib/python3.7/site-packages/numpy/core/fromnumeric.py", line 2734, in amax
    keepdims=keepdims, initial=initial, where=where)
  File "/home/jlenain/local/src/python/anaconda/envs/nectar-dev/lib/python3.7/site-packages/numpy/core/fromnumeric.py", line 87, in _wrapreduction
    return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
ValueError: zero-size array to reduction operation maximum which has no identity
```

**Comment by hashkar** [comment]
Hi Jean-Philippe,
Sorry for the late reply but I recently change my mac and I was (and still)
having some trouble installing all the softwares.  I am right now having
trying trying to re-install the nectarchain packages on my new machine. I
am encountering an error with the command:

pip install https://github.com/cta-observatory/ctapipe_io_nectarcam/archive/master.tar.gz

The error is : Running setup.py install for protozfits ... error
 error: subprocess-exited-with-error × Running setup.py install for
protozfits did not run successfully.
 │ exit code: 1
 ╰─> [28 lines of output]
    running install
    /Users/hashkar/opt/anaconda3/envs/cta/lib/python3.7/site-packages/setuptools/command/install.py:37:
SetuptoolsDeprecationWarning: setup.py install is deprecated. Use
build and pip and other standards-based tools.
     setuptools.SetuptoolsDeprecationWarning,
    running build
    running build_py
    creating build
    creating build/lib.macosx-10.9-x86_64-3.7
    creating build/lib.macosx-10.9-x86_64-3.7/protozfits
    copying python/protozfits/R1_NectarCam_pb2.py ->
build/lib.macosx-10.9-x86_64-3.7/protozfits
    copying python/protozfits/any_array_to_numpy.py ->
build/lib.macosx-10.9-x86_64-3.7/protozfits
    copying python/protozfits/L0_pb2.py ->
build/lib.macosx-10.9-x86_64-3.7/protozfits
    copying python/protozfits/CoreMessages_pb2.py ->
build/lib.macosx-10.9-x86_64-3.7/protozfits
    copying python/protozfits/CDTS_pb2.py ->
build/lib.macosx-10.9-x86_64-3.7/protozfits
    copying python/protozfits/__init__.py ->
build/lib.macosx-10.9-x86_64-3.7/protozfits
    copying python/protozfits/R1_DigiCam_pb2.py ->
build/lib.macosx-10.9-x86_64-3.7/protozfits
    copying python/protozfits/R1_LSTCam_pb2.py ->
build/lib.macosx-10.9-x86_64-3.7/protozfits
    copying python/protozfits/Auxiliary_pb2.py ->
build/lib.macosx-10.9-x86_64-3.7/protozfits
    copying python/protozfits/Proto_R1_pb2.py ->
build/lib.macosx-10.9-x86_64-3.7/protozfits
    copying python/protozfits/CTA_R1_pb2.py ->
build/lib.macosx-10.9-x86_64-3.7/protozfits
    creating build/lib.macosx-10.9-x86_64-3.7/protozfits/tests
    creating build/lib.macosx-10.9-x86_64-3.7/protozfits/tests/resources
    copying python/protozfits/tests/resources/example_9evts_NectarCAM.fits.fz
-> build/lib.macosx-10.9-x86_64-3.7/protozfits/tests/resources
    copying python/protozfits/tests/resources/example_100evts.fits.fz
-> build/lib.macosx-10.9-x86_64-3.7/protozfits/tests/resources
    copying python/protozfits/tests/resources/example_10evts.fits.fz
-> build/lib.macosx-10.9-x86_64-3.7/protozfits/tests/resources
    copying python/protozfits/tests/resources/example_LST_R1_10_evts.fits.fz
-> build/lib.macosx-10.9-x86_64-3.7/protozfits/tests/resources
    copying python/protozfits/tests/resources/example_SST1M_20180822.fits.fz
-> build/lib.macosx-10.9-x86_64-3.7/protozfits/tests/resources
    running build_ext
    error: cmake >= 3.15.0 is required
    [end of output] note: This error originates from a subprocess, and
is likely not a problem with pip.
 WARNING: No metadata found in
/Users/hashkar/opt/anaconda3/envs/cta/lib/python3.7/site-packages
 Rolling back uninstall of protozfits
 Moving to /Users/hashkar/opt/anaconda3/envs/cta/lib/python3.7/site-packages/protozfits-1.11.0.dist-info/
  from /Users/hashkar/opt/anaconda3/envs/cta/lib/python3.7/site-packages/~rotozfits-1.11.0.dist-info
 Moving to /Users/hashkar/opt/anaconda3/envs/cta/lib/python3.7/site-packages/protozfits/
  from /Users/hashkar/opt/anaconda3/envs/cta/lib/python3.7/site-packages/~rotozfits
error: legacy-install-failure× Encountered error while trying to
install package.
╰─> protozfitsnote: This is an issue with the package mentioned above, not pip.
hint: See above for output from the failure

Do you know what this might be about ? Without installing this package
and trying to run the dqm on any un it gives me a similar error to the
one you get on run 2856:

  File "start_calib.py", line 53, in <module>

    reader=EventSource(input_url=path)

  File "/Users/hashkar/opt/anaconda3/envs/cta/lib/python3.7/site-packages/ctapipe/io/eventsource.py",
line 126, in __new__

    subcls = cls._find_compatible_source(input_url)

  File "/Users/hashkar/opt/anaconda3/envs/cta/lib/python3.7/site-packages/ctapipe/io/eventsource.py",
line 308, in _find_compatible_source

    "\t{}".format(input_url, [c.__name__ for c in available_classes])

ValueError: Cannot find compatible EventSource for

	url:/Users/hashkar/Desktop/ashkar_nectar/data/NectarCAM.Run2720.0000.fits.fz

in available EventSources:

	['SimTelEventSource', 'HDF5EventSource']

Cheers,

Halim

**Comment by jlenain** [comment]
Hi @hashkar !

The `ctapipe_io_nectarcam` plugin is actually required, since this is the part responsible for the ability within `ctapipe` to read NectarCAM files.
@tibaldo recently updated this plugin to allow compatibility with `ctapipe` 0.12 (see https://github.com/cta-observatory/ctapipe_io_nectarcam/pull/18). I just submitted a PR to `nectarchain` to reflect these changes to our installation procedure, see https://github.com/cta-observatory/nectarchain/pull/12 for the details. I'd recommend to follow this procedure on your new machine.

**Comment by jlenain** [comment]
Follow-up in https://github.com/cta-observatory/nectarchain/pull/14

**Pull request closed without merging**
